#!/usr/bin/env ruby
require 'fileutils'

# Copy config files.
Dir['config/examples/*'].each do |source|
  destination = "config/#{File.basename(source)}"
  unless File.exist? destination
    FileUtils.cp(source, destination)
    puts "Generated #{destination}"
  end
end

# Run rake tasks.
env = "RAILS_ENV=production"

system "bundle install"
system "rake db:create #{env}"
system "rake db:migrate --trace #{env}"
system "rake db:seed #{env}"