development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: adbase_development
  username:
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: adbase_test
  username:
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: adbase_production
  username:
  password: